name: "vaibhav"   #name of the workflow

on:                          #This defines triggers
  push:
    branches:
      - 'features/**'
      - 'main'
      - 'hotfixes/**'

jobs:
  vaibhavgithub:    #Job ID
    name: vaibhav    #Display name
    runs-on: [self-hosted, Windows, X64, hp]   # <-- use labels, not runner name
    steps:
      - name: Say Hello  #Display name
        run: echo "Hello from Vaibhav's workflow!"  #TASK

      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # Step 3: Azure CLI login (using secrets individually)
      - name: Azure CLI Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

        

