# name: "vaibhav"

# on:
#   push:
#     branches:
#       - 'features/**'
#       - 'main'
#       - 'hotfixes/**'

# jobs:
#   vaibhavgithub:
#     name: vaibhav
#     runs-on: SATYAPRAKASH
#     steps:
#       - name: Say Hello
#         run: echo "Hello from Vaibhav's workflow!"


name: "vaibhav"

on:
  push:
    branches:
      - 'features/**'
      - 'main'
      - 'hotfixes/**'

jobs:
  vaibhavgithub:
    name: vaibhav
    runs-on: [self-hosted, Windows, X64, hp]   # <-- use labels, not runner name
    steps:
      - name: Say Hello
        run: echo "Hello from Vaibhav's workflow!"

