# name: "vaibhav"   #name of the workflow

# on:                          #This defines triggers
#   push:
#     branches:
#       - 'features/**'
#       - 'main'
#       - 'hotfixes/**'

# # jobs:
# #   vaibhavgithub:    #Job ID
# #     name: vaibhav    #Display name
# #     runs-on: [self-hosted, Windows, X64, hp]   # <-- use labels, not runner name
# #     steps:
# #       - name: Say Hello  #Display name
# #         run: echo "Hello from Vaibhav's workflow!"  #TASK

# jobs:
#   terraform:
#     name: Terraform Deploy to Azure
#     runs-on: ubuntu-latest   # Self-hosted runner ho to uske labels lagao
    
#     steps:
#       # Step 1: Checkout repo
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Setup Terraform
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.7.5

#       # Step 3: Azure Login (recommended action instead of manual az login)
#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#           client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

#       # Step 4: Terraform Init
#       - name: Terraform Init
#         run: terraform init

#       # Step 5: Terraform Validate
#       - name: Terraform Validate
#         run: terraform validate

#       # Step 6: Terraform Plan
#       - name: Terraform Plan
#         run: terraform plan -out=tfplan

#       # Step 7: Terraform Apply
#       - name: Terraform Apply
#         run: terraform apply -auto-approve tfplan

name: "vaibhav"   #name of the workflow

on:                          #This defines triggers
  push:
    branches:
      - 'features/**'
      - 'main'
      - 'hotfixes/**'


jobs:
  terraform:
    name: Terraform Deploy to Azure
    runs-on: ubuntu-latest
    environment: AZURE_CLIENT_ID   # 👈 yeh match hona chahiye environment ke naam se

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

